name: Deploy on PR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Run command on remote server
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USER}}
        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        command: |
          cd CoBuy_server;
          git pull;
          docker compose down;
          docker ps;
          docker compose -file docker-compose-prod.yml up -d;
          docker system prune --all --force;
          docker ps;
